server:
  port: 8044

spring:
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # Database Configuration
  datasource:
    url: jdbc:postgresql://10.0.0.233:5432/akillioperasyon
    username: postgres
    password: Tmohelp01*